- hosts: all
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - patch_role
- hosts: gandi_all
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_role
    - build_ssl_role
- hosts: dns_primary
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_dns_primary_role
- hosts: digitalocean_all
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_role
    - build_ssl_role
- hosts: dns_secondary
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_dns_secondary_role
- hosts: mail_secondary
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_mail_secondary_role
- hosts: mail_dumb
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_mail_dumb_role
- hosts: docker
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_docker_role
- hosts: www
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_www_role
- hosts: www.sciencedimension.co.uk
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_mysql_server_role
    - build_mysql_client_role
    - build_wordpress_role
- hosts: www.emfctf.org
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - build_mysql_client_role
    - clean_ctf_role
    - build_ctf_role
