- hosts: gandi_all
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - change_password_role
- hosts: digitalocean_all
  vars:
    admin: "timb"
    ansible_user: "{{ admin }}"
  become: true
  roles:
    - change_password_role
