- name: create ssl-cert group
  group:
    state: present
    name: ssl-cert
- name: install certificate
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/certs"
    owner: "root"
    group: "ssl-cert"
    mode: 0644
  with_items:
    - files/wildcard.nth-dimension.org.uk.pem
    - files/GandiStandardSSLCA2.pem
- name: install key
  copy:
    content: "{{ ssl_key }}"
    dest: "/etc/ssl/private/wildcard.nth-dimension.org.uk.key"
    owner: "root"
    group: "ssl-cert"
    mode: 0600
  no_log: true
