- name: install OpenDKIM
  apt:
    state: latest
    name: opendkim
  notify: restart OpenDKIM
- name: install SpamAssassin
  apt:
    state: latest
    name: spamass-milter
  notify: restart SpamAssassin
- name: install ClamAV
  apt:
    state: latest
    name: clamav-milter
  notify: restart ClamAV
- name: install Sendmail
  apt:
    name: sendmail
    state: latest
- name: configure OpenDKIM
  copy:
    src: "files/opendkim.conf"
    dest: "/etc"
    owner: "opendkim"
    group: "opendkim"
    mode: 0600
- name: create keys
  copy:
    content: "{{ item.key }}"
    dest: "/etc/dkimkeys/{{ item.hostname }}.private"
    owner: "opendkim"
    group: "opendkim"
    mode: 0600
  with_items: "{{ dkim }}"
  no_log: true
- name: configure keys
  copy:
    src: "{{ item }}"
    dest: "/etc/dkimkeys"
    owner: "opendkim"
    group: "opendkim"
    mode: 0600
  with_items:
    - files/keytable
    - files/signingtable
    - files/trustedhosts
  notify: restart OpenDKIM
- name: configure Sendmail
  template:
    src: "{{ item }}"
    dest: "/etc/mail"
    owner: "root"
    group: "root"
    mode: 0600
  with_items:
    - files/aliases
    - files/local-host-names
    - files/relay-domains
    - files/sendmail.mc
- name: configure SSL
  copy:
    src: "files/starttls.m4"
    dest: "/etc/mail/tls"
    owner: "root"
    group: "root"
    mode: 0600
- name: rebuild aliases
  shell: "newaliases"
- name: rebuild config
  shell: "make"
  args:
    chdir: "/etc/mail"
  notify: restart Sendmail
- name: create forwarder
  copy:
    src: "files/forward"
    dest: "/home/{{ admin }}/.forward"
    owner: "{{ admin }}"
    group: "users"
    mode: 0644
- name: UFW allow TCP SMTP
  ufw:
    rule: allow
    direction: in
    proto: "tcp"
    port: 25
- name: UFW allow TCP submission
  ufw:
    rule: allow
    direction: in
    proto: "tcp"
    port: 587
